.TH JASC-PAL-THUMBNAILER 1 2025-09-24
.SH NAME
jasc-pal-thumbnailer \- thumbnailer for jasc palette files
.SH SYNOPSIS
\fBjasc-pal-thumbnailer\fR \fB-s\fR \fIDIM\fR [\fB-i\fR \fIINFILE\fR] [\fB-o\fR \fIOUTFILE\fR]
.SH DESCRIPTION
A GNOME thumbnailer that accepts a jasc palette file
and generates a thumbnail that shows the colors in the palette
.SH OPTIONS
.TP
.BR \-? ", " \-\-help
Displays a help message and exits.
.TP
.BR \-\-version
Displays program version and exits.
.TP
.BR \-s ", " \-\-size =\fIDIM\fR
The pixel dimensions of the generated output file.
.TP
.BR \-i ", " \-\-input =\fIFILE\fR
The input file.
If not specified, reads from stdin.
.TP
.BR \-o ", " \-\-output =\fIFILE\fR
The location to place the output file.
If not specified, writes to stdout.
